# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-http01-controller
  namespace: knative-serving
  labels:
    app.kubernetes.io/name: http01
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: devel
    serving.knative.dev/release: devel
    networking.knative.dev/ingress-provider: http01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-http01-controller
  template:
    metadata:
      labels:
        app: net-http01-controller
        knative.dev/release: devel
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: ko://knative.dev/net-http01/cmd/controller
        args: [
          # Production Let's Encrypt endpoint.
          "-acme-endpoint", "https://acme-v02.api.letsencrypt.org/directory",

          # Staging Let's Encrypt endpoint.
          # "-acme-endpoint", "https://acme-staging-v02.api.letsencrypt.org/directory",
        ]

        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - all
        ports:
        - name: metrics
          containerPort: 9090
        - name: http-challenge
          containerPort: 8080
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: knative.dev/serving
---
apiVersion: v1
kind: Service
metadata:
  name: net-http01-controller
  namespace: knative-serving
  labels:
    networking.knative.dev/ingress-provider: http01
spec:
  type: ClusterIP
  ports:
  - name: http-challenge
    port: 80
    targetPort: 8080
  selector:
    app: net-http01-controller
